### ISSUE TITLE
Set values for constants

### ISSUE THREAD

**Issue by dev-abir** [dev-moss/stackJumpClone#1]
What should be the value for gravitational acceleration, mass of the player and the jumping height(force against gravitational acceleration)? Please provide appropriate values.

**Comment by dev-DTECH** [comment]
can you specify the location where this constants are declared so that i can change it

**Comment by dev-abir** [comment]
> can you specify the location where this constants are declared so that i can change it

You can find it here : src/Misc/Common.h
I may change this path in the future.
